version: '3'
services:
  backend:
    build:
      context: ./SimpleFlask  # Path to your Flask backend directory
    image: lonewolfsdocker/backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./SimpleFlask:/app
  frontend:
    build:
      context: ./preventi-diabete  # Path to your React frontend directory
    image: lonewolfsdocker/frontend:latest
    ports:
      - "3000:3000"  # React is served on port 80 in the container
    depends_on:
      - backend
