version: '3'
services:
  backend:
    build:
      context: ./SimpleFlask
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./preventi-diabete
    ports:
      - "3000:80"  # Serving React app on port 80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
